rewritten API in Promise and brought flexible error handling [POTENTIAL BUG] [REQUIRED TESTING]
gtech-mulearn/mulearn pull request #690
Opened 2023-08-28 23:28 UTC by rajatsandeepsen

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New Feature (non-breaking change which adds functionality)
- [ ] HotFix (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2023-08-28 23:39 UTC, rajatsandeepsen commented
link for testing [mulearn.vercel.app](https://mulearn.vercel.app/)

2023-08-30 14:26 UTC, Jenin82 requested changes

2023-08-30 14:26 UTC, Jenin82 commented on src/App.tsx
don't change the path in app.tsx

2023-08-30 14:28 UTC, rajatsandeepsen commented on src/App.tsx
Aswin paranju 😥

2023-09-01 16:27 UTC, Jenin82 approved these changes
ok to merge

2023-09-02 06:13 UTC, AswinAsok approved these changes

2023-09-02 06:13 UTC, merged